### ISSUE TITLE
Hello from some Gulf Island sailors. 

### ISSUE THREAD

**Issue by jongarrison** [borsboom/current-atlas-tables#1]
My wife and I are sailing up through the Gulf Islands right now (Saturna at the moment - https://stephaniecp.github.io/ahoy/). Can we buy you a drink to thank you for the current tables?  We've done some coding work with the Current Atlas also.  

Thanks!

Jon and Steph

**Comment by borsboom** [comment]
Hi @jongarrison, that's a very kind offer!  For whatever reason I didn't receive an e-mail notification of this issue so very sorry I didn't see it until now.  If you're still in the area and want to visit Mayne, definitely get in touch.  I'd be happy to meet you at either of the public docks :)

**Comment by jongarrison** [comment]
@borsboom Responded in email! :)
