### ISSUE TITLE
Current atlas tables beyond 2020

### ISSUE THREAD

**Issue by ealmealm** [borsboom/current-atlas-tables#2]
Any chance you will be posting Current Atlas Tables beyond 2020?  My group of sea kayakers in Bellingham find your tables extremely valuable and appreciate you making them available.

**Comment by borsboom** [comment]
Yes!  I no longer had the environment that I'd used to generate the tables, with all the tools set up properly (e.g. xtide non-free harmonics files for Canada that the xtide author no longer makes available, the PDF generator, etc.).  That made it difficult to generate the newer tables.  You have given me the impetus to take care of that, and I've added a `Dockerfile` with the correct environment so this'll hopefully be easier next time.

Now there are tables up to 2030 at https://borsboom.io/current-atlas-tables/.  Check it out and let me know if you see any problems.

**Comment by ealmealm** [comment]
Thank you so much.  These tables will be much used by myself and my kayaking friends.Ed Alm
    On Monday, April 15, 2019, 7:00:59 PM PDT, Emanuel Borsboom <notifications@github.com> wrote:  
 
 
Yes! I no longer had the environment that I'd used to generate the tables, with all the tools set up properly (e.g. xtide non-free harmonics files for Canada that the xtide author no longer makes available, the PDF generator, etc.). That made it difficult to generate the newer tables. You have given me the impetus to take care of that, and I've added a Dockerfile with the correct environment so this'll hopefully be easier next time.

Now there are tables up to 2030 at https://borsboom.io/current-atlas-tables/. Check it out and let me know if you see any problems.
